### ISSUE TITLE
Release 1.8 with Java 11 support

### ISSUE THREAD

**Issue by sormuras** [codehaus-plexus/plexus-containers#12]
Older versions fail due to an outdated ASM library being bundled. I'd like to get rid of the `-SNAPSHOT` suffix and the extra `<pluginRepository>` definition.

The underlying issue #10 is fixed already and the `1.8-SNAPSHOT` version runs on Java 11 as expected: https://travis-ci.com/sormuras/junit-platform-maven-plugin/jobs/164616294#L496

**Comment by dsebastien** [comment]
It would indeed be great to get a new version of this plugin. I'm busy trying to migrate to Java 11 and have stumbled upon #10 as well.

**Comment by sormuras** [comment]
@khmarbaise any news here? How can I help to get a release done?

**Comment by cowwoc** [comment]
Please be sure to fix https://github.com/codehaus-plexus/plexus-containers/issues/17 as part of this issue.

**Comment by khmarbaise** [comment]
I've released a version 2.0.0 which contains all fixes (I hope so)... https://github.com/codehaus-plexus/plexus-containers/blob/master/ReleaseNotes.md

**Comment by sormuras** [comment]
Thanks @khmarbaise for all the fixes and the release!

Works like a charm for me: https://travis-ci.com/sormuras/junit-platform-maven-plugin/builds/98919882

✔️
