### ISSUE TITLE
Migrate to Maven 3.0+ api

### ISSUE THREAD

**Issue by slachiewicz** [codehaus-plexus/plexus-containers#15]
Please consider upgrading project to supported 3.0/3.1+ Maven core and drop all 2.0.9 dependencies.

**Comment by khmarbaise** [comment]
Hi, can someone take a look at that ..I already updated the dependencies (on a branch [issue-15](https://github.com/codehaus-plexus/plexus-containers/tree/issue-15)) to Maven core etc. to Maven3.0+ only...but to be honest it looks too easy to me?
