### ISSUE TITLE
plexus-container-default depends on google-collections which conflicts with guava

### ISSUE THREAD

**Issue by johnwatts** [codehaus-plexus/plexus-containers#18]
Guava is an extremely common library and it was renamed early in its lifetime. plexus-container-default still depends on the old version which can make it very easy to have both the old and new versions of the classes in the dependency tree. The latest version of Guava should be a drop-in replacement for  com.google.collections:google-collections:jar:1.0.

https://code.google.com/archive/p/google-collections/

Here is where I encountered the issue. https://github.com/google/error-prone/issues/624

**Comment by khmarbaise** [comment]
To be honest I would like to get rid of google-collections at all..If we would upgrade to guava we will have a library of 2.5 MiB size in comparison of at the moment 625 KiB ...which is from my point of view not a good deal...furthermore based on the code the collections are only used in a single class which is an indicator to replace that either with a different smaller library or implement it completely on our own so we could safe the size completely.
