### ISSUE TITLE
Error using plexus-generate-metadata with a mocked java.sql.Connection in Java 11

### ISSUE THREAD

**Issue by bkiselka** [codehaus-plexus/plexus-containers#30]
A project that ran without errors compiled with JDK 8 using

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.plexus</groupId>
				<artifactId>plexus-component-metadata</artifactId>
				<version>2.1.0</version>
				<executions>
					<execution>
						<id>process-test-classes</id>
						<goals>
							<goal>generate-test-metadata</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```
in pom.xml, compiled with JDK 11 showed the following error and did not generate the file target-classes/META-INF/plexus/components.xml

```
  [ERROR] Failed to execute goal org.codehaus.plexus:plexus-component-metadata:2.1.0:generate-test-metadata (process-test-classes) on project XXX: Error generating test metadata: : Failed to extract descriptors: Unable to load class java.sql.Connection from [list of libraries]
```

As other sub-modules had no problems, I think the reason is that the failing sub-module mocks java.sql.Connection, which is since JDK 9 in an own java module java.sql.

It this enough information to cope with that bug, or do you want a test project?
Many Thanks!

**Comment by slachiewicz** [comment]
hi, probably its' because the plugin can process only classes up to Java 9 and if You run on Java 11, the mocked class would be generated with Java 11 bytecode.

**Comment by slachiewicz** [comment]
Please switch to Eclipse Sisu #59
