### ISSUE TITLE
The following plugins are not marked @threadSafe

### ISSUE THREAD

**Issue by ricardo-de-matos** [codehaus-plexus/plexus-containers#33]
Using goal `generate-metadata` produces the following warning : 

> [WARNING] *****************************************************************
> [WARNING] * Your build is requesting parallel execution, but project      *
> [WARNING] * contains the following plugin(s) that have goals not marked   *
> [WARNING] * as @threadSafe to support parallel building.                  *
> [WARNING] * While this /may/ work fine, please look for plugin updates    *
> [WARNING] * and/or request plugins be made thread-safe.                   *
> [WARNING] * If reporting an issue, report it against the plugin in        *
> [WARNING] * question, not against maven-core                              *
> [WARNING] *****************************************************************
> [WARNING] The following plugins are not marked @threadSafe in 
> [WARNING] org.codehaus.plexus:plexus-component-metadata:2.1.0
> [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
> [WARNING] *****************************************************************

Can this goal be made `threadSafe` ?

**Comment by slachiewicz** [comment]
Please switch to Eclipse Sisu #59
