### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/plexus-containers#59]
This project should be archived and no more cycles spent on it. 

Transition to Eclipse Sisu is possible (is drop-in replacement), that clears migration path to plain Sisu/JSR330.
Do not use this container anymore: not it enforces bad practice, but a proper replacement is already out there.

**Comment by slachiewicz** [comment]
What about to release 2.2 with Java 8 - we should get dependabot notifications - would be easier to upgrade each Project. WDYT?

**Comment by cstamas** [comment]
Why would you do that? What project is using Plexus Container?

**Comment by slachiewicz** [comment]
I think more component-annotations, metadata artefacts

**Comment by michael-o** [comment]
Archive this one, finally.

**Comment by cstamas** [comment]
Note: when this issue was created 2.1.1 was already out (with broken QDox), while 2.1.0 still had all of maven in compile scope. So a "nice" way to retire this would be to have one more release (there are some updates + QDox update), as 3.9.x still needs this plugin, it did not switch to JSR330 only master of Maven did.

Edit: so the PLUGIN is needed by Maven 3.9.x, but plexus container should NOT be used anymore for anything.

**Comment by hboutemy** [comment]
to me, the only thing that is not clear is the plugin migration https://codehaus-plexus.github.io/plexus-containers/plexus-component-metadata/

for annotations, the current page is clear enough https://codehaus-plexus.github.io/plexus-containers/plexus-component-annotations/

**Comment by hboutemy** [comment]
with #121 site publication, I hope we can archive this repository with good-enough practical pointers to know how to migrate

**Comment by slachiewicz** [comment]
I released the final release 2.2.0 with the plexus-default container removed and all other annotations marked as deprecated.
