### ISSUE TITLE
sort entries when generating META-INF/plexus/components.xml

### ISSUE THREAD

**Issue by hboutemy** [codehaus-plexus/plexus-containers#8]
this will help to get "Reproducible/Verifiable Builds": https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318

**Comment by ebourg** [comment]
Patch available here: https://github.com/codehaus-plexus/plexus-containers/pull/7

**Comment by hboutemy** [comment]
#7 merged: thank you Emmanuel
